on: push

jobs:
    compile:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Build Project
              uses: threeal/cmake-action@v2
              with:
                  build-dir: ./build/obj/Release
                  options: |
                      CMAKE_BUILD_TYPE=Release

            - name: Run executable on Unix
              if: runner.os != 'Windows'
              run: ./build/bin/Release/main

            - name: Run executable on Windows
              if: runner.os == 'Windows'
              run: .\build\bin\Release\main.exe

            # - run: ls ./build/bin
