on: push

jobs:
    compile:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Build Project
              uses: threeal/cmake-action@v2
              with:
                  build-dir: ./build/obj/Release
                  options: -DCMAKE_BUILD_TYPE=Release
